services:
  server:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.server
    container_name: gophkeeper-server
    environment:
      - GOPHKEEPER_POSTGRES_DSN=postgres://user:password@postgres:5432/dbname?sslmode=disable
      - GOPHKEEPER_ADDRESS=server:50051
      - GOPHKEEPER_SECRET_KEY=very_complex_secret_key
    ports:
      - "50051:50051"
    depends_on:
      - postgres
    networks:
      - default

  wait:
    image: dokku/wait
    depends_on:
      - postgres
    command: [ "db:${POSTGRES_PORT}" ]

  postgres:
    image: postgres:12.1-alpine
    container_name: gophkeeper-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - default

volumes:
  postgres_data:

networks:
  default:
    driver: bridge